name: trufi_core
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_review: 1.0.0
  cupertino_icons: 0.1.2
  diff_match_patch: 0.3.0
  flare_flutter: 1.6.2
  flutter_compass: 0.3.3
  flutter_map: 0.7.3
  flutter_svg: 0.14.2
  geolocator: 5.1.4+1
  google_api_availability: 2.0.1
  http: 0.12.0+2
  intl: 0.15.8
  intl_translation: 0.17.5
  mockito: 3.0.0
  package_info: 0.4.0+6
  path_provider: 1.3.0
  permission_handler: 3.2.2
  rxdart: 0.22.3
  share: 0.6.2+3
  shared_preferences: 0.5.3+4
  sprintf: 4.0.0
  synchronized: 2.0.2
  url_launcher: 5.1.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: app.trufi.trufi_core
    pluginClass: TrufiCorePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - assets/images/

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
  - family: CircleIcon
    fonts:
    - asset: fonts/CircleIcon.ttf
  - family: GondolaIcon
    fonts:
    - asset: fonts/GondolaIcon.ttf
  - family: CustomIcons
    fonts:
    - asset: fonts/CustomIcons.ttf
